name: kalender
description: A Flutter calendar UI package.
version: 0.0.3
repository: https://github.com/werner-scholtz/kalender.git


environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
