name: kalender
description: This Flutter package offers a versatile Calendar Widget featuring integrated Day, MultiDay, and Month views, all of which come with pre-built functionality. Moreover, it empowers you to effortlessly tailor the visual aspects of the calendar widget to align with your design preferences.
version: 0.0.3
repository: https://github.com/werner-scholtz/kalender.git


environment:
  sdk: '>=2.19.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
