# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Analyze and Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      
      - name: Remove examples folder.
        run: rm -rf examples/
        shell: bash
        working-directory: ./

      - name: Install dependencies
        run: flutter pub get
        shell: bash
        working-directory: ./
      
      - name: Formatting check
        run: dart analyze 
        shell: bash
        working-directory: ./

      - name: Analyse
        run: flutter analyze
        shell: bash
        working-directory: ./

      - name: Run tests
        run: flutter test
        shell: bash
        working-directory: ./