# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Analyze

on:
  pull_request:
    branches: [ main, testing ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.10.0

      - name: Install Flutter
        uses: britannio/action-install-flutter@v1.1

      - name: Install dependencies
        run: flutter pub get

      - name: Formatting check
        run: dart format . --set-exit-if-changed

      - name: Analyse
        run: flutter analyze