# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' 

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    environment: pub.dev
    steps:
      - uses: actions/checkout@v3

      - name: Setup flutter SDK
        uses: subosito/flutter-action@v2
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./

      - name: Publish - dry run
        run: dart pub publish --dry-run
        working-directory: ./

      - name: Publish to pub.dev
        run: dart pub publish -f
        working-directory: ./
  